/**
 * Notion code block language support.
 * Maps common language aliases to the canonical names Notion accepts.
 */

export const SUPPORTED_CODE_BLOCK_LANGUAGES = [
	'abap',
	'arduino',
	'bash',
	'basic',
	'c',
	'clojure',
	'coffeescript',
	'c++',
	'c#',
	'css',
	'dart',
	'diff',
	'docker',
	'elixir',
	'elm',
	'erlang',
	'flow',
	'fortran',
	'f#',
	'gherkin',
	'glsl',
	'go',
	'graphql',
	'groovy',
	'haskell',
	'html',
	'java',
	'javascript',
	'json',
	'julia',
	'kotlin',
	'latex',
	'less',
	'lisp',
	'livescript',
	'lua',
	'makefile',
	'markdown',
	'markup',
	'matlab',
	'mermaid',
	'nix',
	'objective-c',
	'ocaml',
	'pascal',
	'perl',
	'php',
	'plain text',
	'powershell',
	'prolog',
	'protobuf',
	'python',
	'r',
	'reason',
	'ruby',
	'rust',
	'sass',
	'scala',
	'scheme',
	'scss',
	'shell',
	'sql',
	'swift',
	'typescript',
	'vb.net',
	'verilog',
	'vhdl',
	'visual basic',
	'webassembly',
	'xml',
	'yaml',
	'java/c/c++/c#',
] as const;

export type SupportedCodeLang = (typeof SUPPORTED_CODE_BLOCK_LANGUAGES)[number];

export function isSupportedCodeLang(lang: string): lang is SupportedCodeLang {
	return (SUPPORTED_CODE_BLOCK_LANGUAGES as readonly string[]).includes(lang);
}

const LANGUAGE_ALIASES: Record<string, SupportedCodeLang> = {
	abap: 'abap',
	sh: 'shell',
	'shell-script': 'shell',
	zsh: 'shell',
	envrc: 'shell',
	c_cpp: 'c++',
	clojure: 'clojure',
	coffee: 'coffeescript',
	'coffee-script': 'coffeescript',
	cpp: 'c++',
	csharp: 'c#',
	cake: 'c#',
	cakescript: 'c#',
	css: 'css',
	dart: 'dart',
	diff: 'diff',
	udiff: 'diff',
	dockerfile: 'docker',
	Containerfile: 'docker',
	elixir: 'elixir',
	elm: 'elm',
	erlang: 'erlang',
	fsharp: 'f#',
	cucumber: 'gherkin',
	glsl: 'glsl',
	golang: 'go',
	groovy: 'groovy',
	haskell: 'haskell',
	html: 'html',
	xhtml: 'html',
	java: 'java/c/c++/c#',
	javascript: 'javascript',
	js: 'javascript',
	node: 'javascript',
	json: 'json',
	geojson: 'json',
	jsonl: 'json',
	sarif: 'json',
	topojson: 'json',
	julia: 'julia',
	tex: 'latex',
	latex: 'latex',
	less: 'less',
	'less-css': 'less',
	livescript: 'livescript',
	'live-script': 'livescript',
	ls: 'livescript',
	lua: 'lua',
	makefile: 'makefile',
	bsdmake: 'makefile',
	make: 'makefile',
	mf: 'makefile',
	markdown: 'markdown',
	md: 'markdown',
	pandoc: 'markdown',
	matlab: 'matlab',
	octave: 'matlab',
	nix: 'nix',
	nixos: 'nix',
	objectivec: 'objective-c',
	'obj-c': 'objective-c',
	objc: 'objective-c',
	ocaml: 'ocaml',
	pascal: 'pascal',
	delphi: 'pascal',
	objectpascal: 'pascal',
	perl: 'perl',
	cperl: 'perl',
	php: 'php',
	inc: 'php',
	powershell: 'powershell',
	posh: 'powershell',
	pwsh: 'powershell',
	prolog: 'prolog',
	protobuf: 'protobuf',
	proto: 'protobuf',
	python: 'python',
	python3: 'python',
	rusthon: 'python',
	r: 'r',
	Rscript: 'r',
	splus: 'r',
	ruby: 'ruby',
	jruby: 'ruby',
	macruby: 'ruby',
	rake: 'ruby',
	rb: 'ruby',
	rbx: 'ruby',
	rs: 'rust',
	rust: 'rust',
	sass: 'sass',
	scala: 'scala',
	scheme: 'scheme',
	scss: 'scss',
	sql: 'sql',
	typescript: 'typescript',
	ts: 'typescript',
	'visual basic': 'vb.net',
	vbnet: 'vb.net',
	'vb .net': 'vb.net',
	'vb.net': 'vb.net',
	verilog: 'verilog',
	vhdl: 'vhdl',
	wast: 'webassembly',
	wasm: 'webassembly',
	xml: 'xml',
	rss: 'xml',
	xsd: 'xml',
	wsdl: 'xml',
	yaml: 'yaml',
	yml: 'yaml',
	shell: 'shell',
	bash: 'bash',
	python2: 'python',
	py: 'python',
	go: 'go',
	kotlin: 'kotlin',
	swift: 'swift',
};

/**
 * Resolve a language alias/name to the canonical Notion code language.
 * Returns undefined if the language is not recognized.
 */
export function parseCodeLanguage(lang?: string): SupportedCodeLang | undefined {
	if (!lang) return undefined;
	const lower = lang.toLowerCase();
	if (isSupportedCodeLang(lower)) return lower as SupportedCodeLang;
	return LANGUAGE_ALIASES[lower] ?? LANGUAGE_ALIASES[lang] ?? undefined;
}
